#!/bin/bash

# Build script to generate HTML files from JSON exam files
echo "🚀 Building exam HTML files..."

# Check if exams directory exists
if [ ! -d "exams" ]; then
    echo "❌ No exams directory found"
    exit 1
fi

        # Check if templates exist
        if [ ! -f "templates/exam-template.html" ]; then
            echo "❌ No templates/exam-template.html found to use as template"
            exit 1
        fi
        
        if [ ! -f "templates/landing-template.html" ]; then
            echo "❌ No templates/landing-template.html found to use as template"
            exit 1
        fi

# Clean up old generated files (but keep JSON files)
echo "🧹 Cleaning up old generated files..."
rm -f exams/*.html

# Function to generate landing page
generateLandingPage() {
    # Read the landing template
    local template=$(cat templates/landing-template.html)
    
    # Initialize variables
    local exam_sections=""
    local total_exams=0
    
    # Categorize exams
    local universidad_exams=""
    local bachillerato_exams=""
    local practice_exams=""
    
    # Process each JSON file to build exam sections
    for json_file in exams/*.json; do
        if [ -f "$json_file" ]; then
            local exam_name=$(basename "$json_file" .json)
            
            # Read exam title from JSON
            local title=$(grep '"title"' "$json_file" | head -1 | sed 's/.*"title": *"\([^"]*\)".*/\1/')
            
            # Create exam card HTML
            local exam_card="
                <div class='exam-card'>
                    <h3>$title</h3>
                    <a href='exams/$exam_name.html' class='btn'>Comenzar Examen</a>
                </div>"
            
            # Categorize based on filename
            if [[ "$exam_name" == *"universidad"* ]]; then
                universidad_exams="$universidad_exams$exam_card"
            elif [[ "$exam_name" == *"bachillerato"* ]]; then
                bachillerato_exams="$bachillerato_exams$exam_card"
            else
                practice_exams="$practice_exams$exam_card"
            fi
            
            ((total_exams++))
        fi
    done
    
    # Build exam sections HTML
    if [ -n "$universidad_exams" ]; then
        exam_sections="$exam_sections
        <div class='category'>
            <h2>🎓 Exámenes Universitarios</h2>
            <div class='exam-grid'>
                $universidad_exams
            </div>
        </div>"
    fi
    
    if [ -n "$bachillerato_exams" ]; then
        exam_sections="$exam_sections
        <div class='category'>
            <h2>🏫 Exámenes de Bachillerato</h2>
            <div class='exam-grid'>
                $bachillerato_exams
            </div>
        </div>"
    fi
    
    if [ -n "$practice_exams" ]; then
        exam_sections="$exam_sections
        <div class='category'>
            <h2>📝 Exámenes de Práctica</h2>
            <div class='exam-grid'>
                $practice_exams
            </div>
        </div>"
    fi
    
    # Generate the complete landing page HTML
    cat > index.html << EOF
<!-- AUTO-GENERATED FILE - DO NOT MODIFY MANUALLY -->
<!-- Generated by build-exam.sh script on $(date) -->
<!-- Landing page with all available exams -->
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AnSheet - Exámenes Disponibles</title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px; background-color: #f5f5f5; }
        .header { text-align: center; margin-bottom: 40px; }
        .header h1 { color: #2196f3; margin-bottom: 10px; }
        .header p { color: #666; font-size: 1.1em; }
        .category { margin-bottom: 40px; }
        .category h2 { color: #333; border-bottom: 2px solid #2196f3; padding-bottom: 10px; margin-bottom: 20px; }
        .exam-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 20px; }
        .exam-card { background: white; border-radius: 8px; padding: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); transition: transform 0.2s, box-shadow 0.2s; }
        .exam-card:hover { transform: translateY(-2px); box-shadow: 0 4px 8px rgba(0,0,0,0.15); }
        .exam-card h3 { margin: 0 0 15px 0; color: #2196f3; }
        .btn { display: inline-block; background-color: #2196f3; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px; transition: background-color 0.2s; }
        .btn:hover { background-color: #1976d2; }
        .footer { text-align: center; margin-top: 40px; padding: 20px; color: #666; border-top: 1px solid #ddd; }
    </style>
</head>
<body>
    <div class="header">
        <h1>📚 AnSheet - Sistema de Exámenes</h1>
        <p>Selecciona el examen que deseas realizar</p>
    </div>

$exam_sections

    <div class="footer">
        <p>AnSheet - Sistema de generación y calificación de exámenes</p>
        <p>Total de exámenes disponibles: $total_exams</p>
    </div>
</body>
</html>
EOF
    
    echo "✅ Generated: index.html (landing page)"
}

# Counter for generated files
generated_count=0

# Process each JSON file in exams directory
for json_file in exams/*.json; do
    if [ -f "$json_file" ]; then
        # Extract filename without path and extension
        exam_name=$(basename "$json_file" .json)
        
        # Create HTML filename in exams directory
        html_file="exams/${exam_name}.html"
        
        echo "📝 Processing: $exam_name"
        
        # Copy template to new file
        cp templates/exam-template.html "$html_file"
        
        # Add auto-generated comment at the top
        sed -i.bak "1i\\
<!-- AUTO-GENERATED FILE - DO NOT MODIFY MANUALLY -->\\
<!-- Generated by build-exam.sh script on $(date) -->\\
<!-- Source: $exam_name.json -->\\
" "$html_file"
        
        # Replace the BASE_PATH from ./ to ../exams/
        sed -i.bak "s/BASE_PATH = '\.\/';/BASE_PATH = '..\/exams\/';/" "$html_file"
        
        # Replace the exam name in the generateExamSheet call
        sed -i.bak "s/examName = 'exam-template';/examName = '$exam_name';/" "$html_file"
        
        # Remove backup file
        rm "${html_file}.bak"
        
        echo "✅ Generated: $html_file"
        ((generated_count++))
    fi
done

# Generate landing page
echo "📝 Generating landing page..."
generateLandingPage

echo ""
echo "🎉 Build completed!"
echo "📄 Generated $generated_count HTML files:"
ls -la exams/*.html
echo "📄 Generated landing page: index.html" 
