#!/bin/bash

# Script to build HTML exam files from JSON/YAML sources
# This script handles the conversion and embedding of exam data into HTML files

set -e  # Exit on any error

echo "📝 Building HTML exam files..."

# Check if source directory exists
if [ ! -d "source" ]; then
    echo "❌ No source directory found"
    echo "💡 Create the 'source' directory and add YAML files to get started"
    exit 1
fi

# Check if templates exist
if [ ! -f "templates/exam-template.html" ]; then
    echo "❌ No templates/exam-template.html found to use as template"
    echo "💡 Make sure the templates directory contains exam-template.html"
    exit 1
fi

# Check if required Python scripts exist
if [ ! -f "yaml_to_json.py" ]; then
    echo "❌ Error: yaml_to_json.py not found"
    exit 1
fi

if [ ! -f "embed_exam_data.py" ]; then
    echo "❌ Error: embed_exam_data.py not found"
    exit 1
fi

# Clean up old generated HTML files (but keep JSON files)
echo "🧹 Cleaning up old generated HTML files..."
rm -f exams/*.html

# Convert YAML files to JSON (if any)
echo "🔄 Converting YAML files to JSON..."

for yaml_file in source/*.yaml; do
    if [ -f "$yaml_file" ]; then
        echo "📝 Converting: $(basename "$yaml_file")"
        python3 yaml_to_json.py "$yaml_file"
        if [ $? -ne 0 ]; then
            echo "❌ Error converting $(basename "$yaml_file")"
            exit 1
        fi
    fi
done

# Counter for generated files
generated_count=0

# Process each JSON file in exams directory (including converted ones)
for json_file in exams/*.json; do
    if [ -f "$json_file" ]; then
        # Extract filename without path and extension
        exam_name=$(basename "$json_file" .json)
        
        # Create HTML filename in exams directory
        html_file="exams/${exam_name}.html"
        
        echo "📝 Processing: $exam_name"
        
        # Copy template to new file
        cp templates/exam-template.html "$html_file"
        
        # Add auto-generated comment at the top
        sed -i.bak "1i\\
<!-- AUTO-GENERATED FILE - DO NOT MODIFY MANUALLY -->\\
<!-- Generated by build-html-exams.sh script -->\\
<!-- Source: $exam_name.yaml -->\\
" "$html_file"

        # Embed exam data directly in the HTML file
        python3 embed_exam_data.py "$json_file" "$html_file"
        if [ $? -ne 0 ]; then
            echo "❌ Error embedding exam data in $(basename "$html_file")"
            exit 1
        fi
        
        # Remove backup file
        rm "${html_file}.bak"
        
        echo "✅ Generated: $html_file"
        ((generated_count++))
    fi
done

echo ""
echo "✅ HTML exam build completed!"
echo "📄 Generated $generated_count HTML files:"
ls -la exams/*.html 
