#!/bin/bash

# Script to build the landing page from available exam JSON files
# This script generates the main index.html with categorized exam cards

set -e  # Exit on any error

echo "📝 Building landing page..."

# Check if templates exist
if [ ! -f "templates/landing-template.html" ]; then
    echo "❌ No templates/landing-template.html found to use as template"
    echo "💡 Make sure the templates directory contains landing-template.html"
    exit 1
fi

# Check if exams directory exists
if [ ! -d "exams" ]; then
    echo "❌ No exams directory found"
    echo "💡 Run build-html-exams.sh first to generate exam files"
    exit 1
fi

# Function to generate landing page
generateLandingPage() {
    # Read the landing template
    local template=$(cat templates/landing-template.html)
    
    # Initialize variables
    local exam_sections=""
    
    # Categorize exams
    local universidad_exams=""
    local bachillerato_exams=""
    local other_exams=""
    
    # Process each JSON file to build exam sections (including converted YAML files)
    for json_file in exams/*.json; do
        if [ -f "$json_file" ]; then
            local exam_name=$(basename "$json_file" .json)
            
            # Read exam title from JSON
            local title=$(grep '"title"' "$json_file" | head -1 | sed 's/.*"title": *"\([^"]*\)".*/\1/')
            
            # Create exam card HTML
            local exam_card="
                <div class='exam-card'>
                    <h3>$title</h3>
                    <a href='exams/$exam_name.html' class='btn'>Comenzar Examen</a>
                </div>"
            
            # Categorize based on filename
            if [[ "$exam_name" == *"universidad"* ]]; then
                universidad_exams="$universidad_exams$exam_card"
            elif [[ "$exam_name" == *"bachillerato"* ]] || [[ "$exam_name" == *"comipems"* ]]; then
                bachillerato_exams="$bachillerato_exams$exam_card"
            else
                other_exams="$other_exams$exam_card"
            fi
        fi
    done
    
    # Build exam sections HTML
    if [ -n "$universidad_exams" ]; then
        exam_sections="$exam_sections
        <div class='category'>
            <h2>🎓 Exámenes Universidad</h2>
            <div class='exam-grid'>
                $universidad_exams
            </div>
        </div>"
    fi
    
    if [ -n "$bachillerato_exams" ]; then
        exam_sections="$exam_sections
        <div class='category'>
            <h2>🏫 Exámenes Bachillerato</h2>
            <div class='exam-grid'>
                $bachillerato_exams
            </div>
        </div>"
    fi
    
    if [ -n "$other_exams" ]; then
        exam_sections="$exam_sections
        <div class='category'>
            <h2>📝 Otros Exámenes</h2>
            <div class='exam-grid'>
                $other_exams
            </div>
        </div>"
    fi
    
    # Replace placeholders in template using a file-based approach
    # Write template to temporary file
    echo "$template" > temp_template.html
    
    # Replace placeholders one by one
    
    # Fix CSS path for the generated index.html (change ../index.css to index.css)
    sed -i.bak "s|../index.css|index.css|g" temp_template.html
    
    # For exam sections, we need to handle multiline content carefully
    # Create a temporary file with the exam sections
    echo "$exam_sections" > temp_exam_sections.html
    
    # Use awk to replace the placeholder with file content
    awk '/{{EXAM_SECTIONS}}/ { system("cat temp_exam_sections.html"); next } { print }' temp_template.html > temp_final.html
    
    local generated_content=$(cat temp_final.html)
    
    # Clean up temporary files
    rm temp_template.html temp_template.html.bak temp_exam_sections.html temp_final.html
    
    # Add auto-generated comment at the top
    cat > index.html << EOF
<!-- AUTO-GENERATED FILE - DO NOT MODIFY MANUALLY -->
<!-- Generated by build-landing-page.sh script -->
<!-- Landing page with all available exams -->

$generated_content
EOF
    
    echo "✅ Generated: index.html (landing page)"
}

# Generate landing page
generateLandingPage

echo ""
echo "✅ Landing page build completed!"
echo "📄 Generated landing page: index.html" 
